# Пожалуйста, решите следующие задачи

1. Пожалуйста, сгенерируйте данные в формате numpy, который состоит из 8 элементов, и каждый элемент состоит из 3 признаков. Вы можете использовать любые числа для признаков.

In [3]:
import numpy as np

np.random.seed(21)
X = []
for _ in range(8):
    row = []
    for _ in range(3):
        row.append(np.random.randint(0,11))
    X.append(row)
X = np.array(X)
X

array([[ 9,  8,  4],
       [ 0,  0,  8],
       [ 3,  2,  1],
       [10,  8,  9],
       [ 6, 10,  0],
       [ 4,  6,  4],
       [ 4,  7,  8],
       [ 9,  5,  6]])

2. Теперь сгенерируйте массив y, состоящий из 8 чисел, равных 0 или 1.

In [4]:
np.random.seed(21)
y = np.array([np.random.randint(0,2) for i in range(8)])
y

array([1, 1, 0, 0, 0, 0, 0, 1])

3. Теперь используйте функцию train_test_split, чтобы разделить данные на части обучения и тестирования. Вы можете использовать 50% данных для обучения и остальные для тестирования.

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=21)

4. Теперь создайте еще один массив numpy, состоящий из 4 чисел, где каждое число равно 0 или 1. Этот массив будет вашим прогнозом.

In [9]:
np.random.seed(21)
prediction = np.array([np.random.randint(0,2) for i in range(4)])
prediction

array([1, 1, 0, 0])

5. Используйте свой прогноз и набор тестов для расчета precision.

In [10]:
from sklearn.metrics import precision_score

precision = precision_score(y_test,prediction)
print(f"Precision:{precision}")

Precision:0.5


6. Используйте свой прогноз и тестовый набор для расчета recall.

In [11]:
from sklearn.metrics import recall_score

recall = recall_score(y_test, prediction)
print(f"Recall:{recall}")

Recall:1.0


7. Используйте свой прогноз и набор тестов, чтобы рассчитать F1 score.

In [12]:
from sklearn.metrics import f1_score

f1 = f1_score(y_test,prediction)
print(f"F1 score:{f1}")

F1 score:0.6666666666666666


8. Используйте свой прогноз и набор тестов для расчета точности.

In [14]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test,prediction)
print(f"Accuracy:{accuracy}")

Accuracy:0.75
