1. Для вас даны следующие данные, где у вас есть количество комнат, площадь квартиры и год постройки и стоимость квартиры. На основе этих данных вы должны создать ML-модель, которая сможет прогнозировать стоимость квартиры. Вы должны определить feature vector входных данных и метки (ground truth labels). Во-первых, определите feature vector входных данных.

a. $x_{1}$ - количество комнат \
b. $x_{1}$ - количество комнат, $x_{2}$ - год постройки \
c. $x_{1}$ - количество комнат, $x_{2}$ - стоимость квартиры \
d. $x_{1}$ - количество комнат, $x_{2}$ - год постройки, $x_{3}$ - площадь квартиры

**Ответ**: d

2. Для Вас приведены такие данные как: количество комнат - 3, район - Медеуский район, год постройки - 1956 и стоимость - 100000. Если предположить, что есть только три района, такие как Медеу, Бостандык и Алмалы. Тогда вы должны описать эти данные в числовой форме. Подсказка: вы можете использовать one-hot-encoding для данных района.

In [5]:
import numpy as np

x1 = np.array([3, 1, 0, 0, 1956])
y1 = np.array([100000])


3. Для Вас приведены такие данные как: количество комнат - 2, площадь - Бостандыкский район, год постройки - 1976 и стоимость - 120000. Если предположить, что есть только три района, такие как Медеу, Бостандык и Алмалы. Тогда вы должны описать эти данные в числовой форме. Подсказка: вы можете использовать one-hot-encoding для данных района.

In [9]:
x2 = np.array([2, 0, 1, 0, 1976])
y2 = np.array([120000])

4. Для Вас приведены такие данные как: количество комнат - 3, площадь - Алмалинский район, год постройки - 2000 и стоимость - 170000. Если предположить, что есть только три района, такие как Медеу, Бостандык и Алмалы. Тогда вы должны описать эти данные в числовой форме. Подсказка: вы можете использовать one-hot-encoding для данных района.

In [10]:
x3 = np.array([3, 0, 0, 1, 2000])
y3 = np.array([170000])

5. Объедините все векторы признаков в один список (X) и все метки в другой список (y).

In [11]:
X = np.array([x1, x2,x3])
y = np.array([y1, y2, y3])

6. Затем разделите данные на обучающий и тестовый наборы, где 33% данных будут переданы тестовому набору, а остальные будут переданы обучающему набору.

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=21)
print(f"X train:\n{X_train}")
print(f"y train:\n{y_train}")
print(f"X test:\n{X_test}")
print(f"y test:\n{y_test}")

X train:
[[   3    0    0    1 2000]
 [   2    0    1    0 1976]]
y train:
[[170000]
 [120000]]
X test:
[[   3    1    0    0 1956]]
y test:
[[100000]]
