# Пожалуйста, ответьте на следующие вопросы и решите следующие задачи

1. Что такое обучения без учителя? \
a. Когда у нас есть входные данные и соответствующие метки для каждых входных данных \
b. Когда у нас есть входные данные и нет метки для каждого входного данных \
c. Когда мы учимся, делая ошибки и вознаграждая за определенные действия

**Ответ**: b

2. Что такое обучение с подкреплением? \
a. Когда у нас есть входные данные и соответствующие метки для каждых входных данных \
b. Когда у нас есть входные данные и для каждого входного данных нет метки \
c. Когда мы учимся, делая ошибки и вознаграждая за определенные действия

**Ответ**: c

3. Какого множества не существует? \
a. train \
b. validation \
c. test \
d. prediction

**Ответ**: d

4. Что такое delta? \
a. Разница между прогнозом и меткой \
b. Метод обучения \
c. Метка \
d. Входные данные

**Ответ**: a

5. Большинство данных используется для ... \
a. testing \
b. training \
c. validation

**Ответ**: b

6. Сколько folds у нас в есть методе 3 fold cross validation? \
a. 2 \
b. 3 \
c. 4 \
d. 5

**Ответ**: b

7. Пожалуйста, сгенерируйте данные в формате numpy, который состоит из 10 элементов, и каждый элемент состоит из 5 признаков. Вы можете использовать любые числа для признаков.

In [23]:
import numpy as np
np.random.seed(105)

X = []

for _ in range(10):
    row = []
    for _ in range(5):
        row.append(np.random.randint(0,11))
    X.append(row)
X = np.array(X)
print(X)

[[ 0  5  6  9  4]
 [ 0  0  4  0  4]
 [ 1  6  9  9  3]
 [ 9  4  6  6  9]
 [ 4 10  2  4  1]
 [ 1  7  6  8  5]
 [10  3  9  7  6]
 [ 9  2  5  6  7]
 [ 0  2  6 10  8]
 [ 9  3  1  4  1]]


8. Теперь сгенерируйте массив y, состоящий из 10 чисел, равных 0 или 1.

In [28]:
np.random.seed(21)
y = np.array([np.random.randint(0,2) for i in range(10)])
y

array([1, 1, 0, 0, 0, 0, 0, 1, 0, 0])

9. Теперь используйте функцию train_test_split, чтобы разделить данные на части обучения и тестирования.

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =0.3, random_state=21)

print(f"X train:\n{X_train}")
print(f"y train:\n{y_train}")
print(f"X test:\n{X_test}")
print(f"y test:\n{y_test}")

X train:
[[ 9  4  6  6  9]
 [ 1  7  6  8  5]
 [10  3  9  7  6]
 [ 0  5  6  9  4]
 [ 4 10  2  4  1]
 [ 0  2  6 10  8]
 [ 9  3  1  4  1]]
y train:
[0, 0, 0, 1, 0, 0, 0]
X test:
[[0 0 4 0 4]
 [1 6 9 9 3]
 [9 2 5 6 7]]
y test:
[1, 0, 1]
