1. Для вас предоставлены следующие библиотеки

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from sklearn import datasets
from sklearn.model_selection import train_test_split , KFold
from sklearn.preprocessing import Normalizer
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

from collections import Counter

2. Также вы можете получить набор данных радужной оболочки, используя следующий код

In [2]:
# import iris dataset
iris = datasets.load_iris()
# np.c_ is the numpy concatenate function
iris_df = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                      columns= iris['feature_names'] + ['target'])
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

3. Используйте столбцы: "sepal length, sepal width, petal length, petal width" в качестве вектора признаков и используйте столбец «target» в качестве метки.

In [4]:
X = iris_df[['sepal length (cm)','sepal width (cm)','petal length (cm)','petal width (cm)']].values
y = iris_df[['target']].values

4. Используйте 20% данных для тестирования и остальные для обучения

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=21)

5. Распечатайте количество образцов в train и test наборе.

In [6]:
print(X_train, y_train)
print(X_test, y_test)

[[4.5 2.3 1.3 0.3]
 [7.9 3.8 6.4 2. ]
 [5.9 3.2 4.8 1.8]
 [5.1 3.8 1.6 0.2]
 [6.2 2.8 4.8 1.8]
 [6.5 2.8 4.6 1.5]
 [6.  3.4 4.5 1.6]
 [5.8 2.8 5.1 2.4]
 [4.4 3.  1.3 0.2]
 [5.8 2.7 5.1 1.9]
 [5.9 3.  5.1 1.8]
 [6.3 3.4 5.6 2.4]
 [5.7 2.5 5.  2. ]
 [6.2 2.9 4.3 1.3]
 [6.9 3.1 5.1 2.3]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.3 3.  1.1 0.1]
 [6.2 2.2 4.5 1.5]
 [4.8 3.4 1.6 0.2]
 [6.9 3.1 4.9 1.5]
 [5.  3.3 1.4 0.2]
 [6.7 3.1 4.4 1.4]
 [7.7 2.6 6.9 2.3]
 [5.7 2.8 4.5 1.3]
 [5.8 2.7 4.1 1. ]
 [4.6 3.1 1.5 0.2]
 [5.1 3.5 1.4 0.3]
 [7.7 3.  6.1 2.3]
 [4.7 3.2 1.6 0.2]
 [5.4 3.7 1.5 0.2]
 [4.6 3.6 1.  0.2]
 [4.7 3.2 1.3 0.2]
 [5.4 3.4 1.5 0.4]
 [5.7 2.9 4.2 1.3]
 [5.5 2.5 4.  1.3]
 [5.2 3.5 1.5 0.2]
 [6.7 2.5 5.8 1.8]
 [6.4 3.2 4.5 1.5]
 [4.9 3.  1.4 0.2]
 [5.4 3.9 1.3 0.4]
 [4.9 2.5 4.5 1.7]
 [6.7 3.1 4.7 1.5]
 [4.9 3.1 1.5 0.2]
 [6.5 3.  5.8 2.2]
 [5.  2.3 3.3 1. ]
 [6.1 2.6 5.6 1.4]
 [5.  3.5 1.6 0.6]
 [6.4 2.7 5.3 1.9]
 [5.1 3.4 1.5 0.2]
 [4.6 3.2 1.4 0.2]
 [6.  2.9 4.5 1.5]
 [6.5 3.  5.

6. Вы можете использовать нормализованные данные, используя следующий код

In [7]:
scaler= Normalizer().fit(X_train) # the scaler is fitted to the training set
normalized_x_train= scaler.transform(X_train) # the scaler is applied to the training set
normalized_x_test= scaler.transform(X_test) # the scaler is applied to the test set

print(normalized_x_train.shape, normalized_x_test.shape)
print(y_train.shape, y_test.shape)

(120, 4) (30, 4)
(120, 1) (30, 1)


7. Обучите модель с помощью KNN

In [8]:
model = KNeighborsClassifier(n_neighbors=6)
model.fit(normalized_x_train, y_train)

C:\Users\Swift\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=6)

8. Сделайте классификацию, используя обученную модель

In [10]:
prediction = model.predict(normalized_x_test)

9. Рассчитайте точность

In [11]:
print(f"Accuracy:{accuracy_score(y_test, prediction)}")

Accuracy:0.9666666666666667
