1. Основы NumPy: Создайте массив NumPy из списка, содержащего числа от 1 до 10. Выведите этот массив.

In [10]:
import numpy as np

arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


2. Операции с массивами: Создайте два массива NumPy: первый с элементами от 1 до 5, второй - с элементами от 6 до 10. Выполните поэлементное сложение этих массивов.

In [11]:
arr1 = np.arange(1,6)
arr2 = np.arange(6,11)
print(arr1+arr2)

[ 7  9 11 13 15]


3. Индексация и срезы: Создайте одномерный массив из первых 10 целых чисел. Выведите все четные элементы этого массива (используйте индексацию также как для списков).

In [18]:
arr1 = np.arange(10)

print(arr1[::2])

[0 2 4 6 8]
