Задача 1 - Сложение и изменение формы массивов:

● Создайте два одномерных массива из случайных целых чисел от 1 до 10.

● Выполните поэлементное сложение этих двух массивов.

● Измените форму полученного массива на матрицу 2x5.

● Посчитайте среднее значение

In [13]:
import numpy as np

A = np.random.randint(1,10,size=10)
B = np.random.randint(1,10,size=10)
print(f'A:{A}\nB:{B}\n')
print(f'A+B:{A+B}\n')
C = np.reshape(A+B,(2,5))
print(f'C:{C}')
print(f'Mean:{C.mean()}')

A:[6 3 2 9 2 1 6 1 9 9]
B:[6 3 8 8 8 4 6 4 4 8]

A+B:[12  6 10 17 10  5 12  5 13 17]

C:[[12  6 10 17 10]
 [ 5 12  5 13 17]]
Mean:10.7


Задача 2 - Работа со срезами и формами:

● Создайте массив размером 3x3 и выведите его первую строку и первый столбец.

● Измените форму массива с помощью функции reshape и выведите его новую форму.

● Используйте функцию flatten, чтобы преобразовать массив в одномерный.

In [24]:
a = np.random.randint(10,size=(3,3)); print(a,'\n')
print(a[0][0])
print(f'reshape:{a.reshape(1,9)}\n')
a = a.flatten()
print(a)

[[4 7 7]
 [9 3 7]
 [0 2 4]] 

4
reshape:[[4 7 7 9 3 7 0 2 4]]

[4 7 7 9 3 7 0 2 4]


Задача 3 - Генерация массива и объединение столбцов:

● Создайте двумерный массив размером 4x3 с случайными целыми числами от 1 до 10.

● Объедините столбцы этого массива в один столбец с использованием vstack.

In [33]:
a = np.random.randint(1,10,size=(4,3))
print(a,'\n')
b = np.vstack((a[:,0],a[:,1],a[:,2]))
print(b,'\n')
print(b.flatten())

[[8 4 2]
 [2 7 4]
 [4 6 7]
 [9 8 1]] 

[[8 2 4 9]
 [4 7 6 8]
 [2 4 7 1]] 

[8 2 4 9 4 7 6 8 2 4 7 1]


Задача 4 - Генерация массива и индексирование:

● Создайте массив из 9 случайных чисел от 1 до 30.

● Найдите индекс максимального значения в массиве и выведите это значение.

In [50]:
a = np.random.randint(1,31,size=9)
print(a)
print(np.argmax(a))

[21 11  3  3 30 19  2 10 22]
4


Задача 5 - Операции над массивами:

● Создайте два массива, каждый размером 2x2, состоящих из случайных целых чисел от 1 до 5.

● Транспонируйте один из массивов.

● Сложите транспонированный массив с другим массивом.



In [53]:
a = np.random.randint(1,6,size=(2,2))
print(f'a:{a}\n')
b = np.random.randint(1,6,size=(2,2))
print(f'b:{b}\n')
a_T = a.transpose()
print(f'a^T:{a_T}\n')
print(f'a+b:{a_T+b}')

a:[[4 5]
 [3 3]]

b:[[3 3]
 [2 3]]

a^T:[[4 3]
 [5 3]]

a+b:[[7 6]
 [7 6]]
